version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: paynet_process_app
        volumes:
            - .:/var/www
        working_dir: /var/www
        depends_on:
            - redis
            - mysql
        ports:
            - "9000:9000"
        networks:
            - appnet
        environment:
            PHP_OPCACHE_VALIDATE_TIMESTAMPS: 0

    nginx:
        image: nginx:alpine
        container_name: paynet_process_nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - appnet

    redis:
        image: redis:alpine
        container_name: paynet_process_redis
        ports:
            - "6379:6379"
        networks:
            - appnet

    mysql:
        image: mysql:8.0
        container_name: paynet_process_mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: paynet
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: paynet
            MYSQL_PASSWORD: secret
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - appnet

volumes:
    mysql_data:

networks:
    appnet:
        driver: bridge
